{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "dPODQoCV5IVI"
      },
      "outputs": [],
      "source": [
        "import random\n",
        "import time\n",
        "import sys\n",
        "\n",
        "sys.setrecursionlimit(20000)\n",
        "\n",
        "comparisons = 0\n",
        "\n",
        "\n",
        "# Partition function\n",
        "def partition(arr, low, high):\n",
        "    global comparisons\n",
        "\n",
        "    pivot = arr[high]\n",
        "    i = low - 1\n",
        "\n",
        "    for j in range(low, high):\n",
        "        comparisons += 1\n",
        "\n",
        "        if arr[j] <= pivot:\n",
        "            i += 1\n",
        "            arr[i], arr[j] = arr[j], arr[i]\n",
        "\n",
        "    arr[i + 1], arr[high] = arr[high], arr[i + 1]\n",
        "\n",
        "    return i + 1\n",
        "\n",
        "\n",
        "# Deterministic Quick Sort\n",
        "def deterministic_quicksort(arr, low, high):\n",
        "    if low < high:\n",
        "        pi = partition(arr, low, high)\n",
        "\n",
        "        deterministic_quicksort(arr, low, pi - 1)\n",
        "        deterministic_quicksort(arr, pi + 1, high)\n",
        "\n",
        "\n",
        "# Randomized Quick Sort\n",
        "def randomized_quicksort(arr, low, high):\n",
        "    if low < high:\n",
        "\n",
        "        # Choose a random pivot\n",
        "        rand_idx = random.randint(low, high)\n",
        "\n",
        "        # Move random pivot to the last position\n",
        "        arr[rand_idx], arr[high] = arr[high], arr[rand_idx]\n",
        "\n",
        "        pi = partition(arr, low, high)\n",
        "\n",
        "        randomized_quicksort(arr, low, pi - 1)\n",
        "        randomized_quicksort(arr, pi + 1, high)\n",
        "\n",
        "\n",
        "# Function to run and measure sorting\n",
        "def run_test(sort_fn, arr):\n",
        "\n",
        "    global comparisons\n",
        "\n",
        "    a = arr[:]\n",
        "\n",
        "    comparisons = 0\n",
        "\n",
        "    start = time.perf_counter()\n",
        "\n",
        "    sort_fn(a, 0, len(a) - 1)\n",
        "\n",
        "    elapsed = (time.perf_counter() - start) * 1000\n",
        "\n",
        "    return comparisons, elapsed\n",
        "\n",
        "\n",
        "# Number of elements\n",
        "N = 5000\n",
        "\n",
        "\n",
        "# Create test cases\n",
        "test_cases = {\n",
        "    \"Random\": [random.randint(1, 100000) for _ in range(N)],\n",
        "\n",
        "    \"Sorted\": list(range(N)),\n",
        "\n",
        "    \"Reverse\": list(range(N, 0, -1)),\n",
        "\n",
        "    \"Nearly Sorted\": list(range(N))\n",
        "}\n",
        "\n",
        "\n",
        "# Make Nearly Sorted input slightly shuffled\n",
        "ns = test_cases[\"Nearly Sorted\"]\n",
        "\n",
        "for _ in range(N // 20):\n",
        "    i = random.randint(0, N - 1)\n",
        "    j = random.randint(0, N - 1)\n",
        "\n",
        "    ns[i], ns[j] = ns[j], ns[i]\n",
        "\n",
        "\n",
        "# Print table heading\n",
        "print(\"{:<16} {:>12} {:>14} {:>12} {:>14}\".format(\n",
        "    \"Input Type\",\n",
        "    \"DQS Comps\",\n",
        "    \"DQS Time(ms)\",\n",
        "    \"RQS Comps\",\n",
        "    \"RQS Time(ms)\"\n",
        "))\n",
        "\n",
        "print(\"-\" * 72)\n",
        "\n",
        "\n",
        "# Run tests\n",
        "for case, arr in test_cases.items():\n",
        "\n",
        "    d_comps, d_time = run_test(\n",
        "        deterministic_quicksort,\n",
        "        arr\n",
        "    )\n",
        "\n",
        "    r_comps, r_time = run_test(\n",
        "        randomized_quicksort,\n",
        "        arr\n",
        "    )\n",
        "\n",
        "    print(\"{:<16} {:>12} {:>14.2f} {:>12} {:>14.2f}\".format(\n",
        "        case,\n",
        "        d_comps,\n",
        "        d_time,\n",
        "        r_comps,\n",
        "        r_time\n",
        "    ))"
      ]
    }
  ]
}